/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2018-12-10 08:41:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardWrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/include/topmenu.jsp", Long.valueOf(1543563133476L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/style.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/jquery-ui.css\">\r\n");
      out.write("<script src=\"/script/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"/script/jquery-ui.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function fn_action() {\r\n");
      out.write("\tvar f = document.frm100;\r\n");
      out.write("\t\r\n");
      out.write("\tif(f.title.value == \"\") {\r\n");
      out.write("\t\talert(\"제목을 입력해주세요.\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(f.pwd.value == \"\") {\r\n");
      out.write("\t\talert(\"암호를 입력해주세요.\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tf.submit();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"jb-container\">\r\n");
      out.write("\t<div id=\"jb-header\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String id = (String)session.getAttribute("SessionMemberId");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"width:100%;\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"div_topmenu\">\r\n");
      out.write("\t<table align=\"center\" cellspacing=\"0\">\r\n");
      out.write("\t\t<colgroup>\r\n");
      out.write("\t\t\t<col width=\"17%\"/>\r\n");
      out.write("\t\t\t<col width=\"17%\"/>\r\n");
      out.write("\t\t\t<col width=\"17%\"/>\r\n");
      out.write("\t\t\t<col width=\"17%\"/>\r\n");
      out.write("\t\t\t<col width=\"17%\"/>\r\n");
      out.write("\t\t\t<col width=\"17%\"/>\r\n");
      out.write("\t\t</colgroup>\r\n");
      out.write("\t\t<tr >\r\n");
      out.write("\t\t\t<td><a href=\"/MainHome.do\">홈</a></td>\r\n");
      out.write("\t   \t\t<td><a href=\"/boardList.do\">여행지</a></td>\r\n");
      out.write("\t    \t<td><a href=\"/reBoardList.do\">축제</a></td>\r\n");
      out.write("\t    \t<td><a href=\"/rschList.do\">커뮤니티</a></td>\r\n");
      out.write("\t    \t<td><a href=\"/rschList.do\">주변여행지</a></td>\r\n");
      out.write("\t\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write(" \t\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write(" \t<div id=\"jb-content\">\r\n");
      out.write("\r\n");
      out.write("<form name=\"frm100\" method=\"post\" action=\"/boardWriteSave.do\">\r\n");
      out.write("<table border=\"1\" width=\"600\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>제목</th>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"title\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>암호</th>\r\n");
      out.write("\t\t<td><input type=\"password\" name=\"pwd\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>글쓴이</th>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"name\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>내용</th>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t<textarea name=\"content\" rows=\"5\" cols=\"70\"></textarea>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th colspan=\"2\">\r\n");
      out.write("\t\t\t<button type=\"button\" onclick=\"fn_action()\">저장</button>\r\n");
      out.write("\t\t\t<button type=\"reset\">취소</button>\r\n");
      out.write("\t\t\t<!-- <input type=\"button\" value=\"저장\" onclick=\"fn_action()\">\r\n");
      out.write("\t\t\t<input type=\"reset\"  value=\"취소\"> -->\r\n");
      out.write("\t\t</th>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"jb-sidebar\">\r\n");
      out.write("        <h2>Sidebar</h2>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li>Lorem</li>\r\n");
      out.write("          <li>Ipsum</li>\r\n");
      out.write("          <li>Dolor</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"jb-footer\">\r\n");
      out.write("        <p>Copyright</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
